### ISSUE TITLE
error parsing variables from aseg gdf file

### ISSUE THREAD

**Issue by Neil-Symington** [usgs/gspy#11]
I am getting errors while parsing variables from an aseg gdf file (see the attached notebook. I don't think the issue comes from the dfn file as I can open it in geosoft without issue. I can provide more details including the input data if needed
[gspy_parsing_issue.pdf](https://github.com/usgs/gspy/files/12711132/gspy_parsing_issue.pdf)

**Comment by leonfoks** [comment]
Hi Neil,

Could you please attach the DFN and just a few points in the data file and we can check?

Thanks!
