### ISSUE TITLE
Confusion with bounds defined for dimensions that are simply discrete values

### ISSUE THREAD

**Issue by leonfoks** [usgs/gspy#2]
Re-visit dimensions with discrete "center" values but perhaps no defined bounds.  Double check CF convention and their note on this

**Comment by bminsley** [comment]
check discrete-axis notes? https://cfconventions.org/cf-conventions/cf-conventions.html#discrete-axis

**Comment by leonfoks** [comment]
Need to double check which things actually need bounds and when.  i.e. coordinates vs dimensions and whether they are discrete or not.

**Comment by leonfoks** [comment]
After the move to use xarray accessors we now have extra keywords that specify coordinates vs dimensions and whether bounds get added or not.
